/******************************************************************************
 * @file    EXTI.h
 * @brief   External interrupt interface for the Visitor Counter sensors.
 *
 *          Provides sensor event flags and the public interface for EXTI
 *          initialization, sensor re-arm processing, and interrupt handlers.
 *
 * @author  Balaji M
 * @target  STM32U083RC
 ******************************************************************************/

#ifndef EXTI_H
#define EXTI_H

#include <stdint.h>


/* Sensor event flags generated by the EXTI interrupt handlers */
extern volatile uint8_t S1_Flag;
extern volatile uint8_t S2_Flag;
extern volatile uint8_t S3_Flag;
extern volatile uint8_t S4_Flag;


/******************************************************************************
 * @brief Initializes EXTI configuration for all four IR sensors.
 ******************************************************************************/
void EXTI_Init(void);


/******************************************************************************
 * @brief Re-arms sensors after their beams become clear.
 *
 *        Called continuously from the main application loop.
 ******************************************************************************/
void EXTI_Process(void);


/******************************************************************************
 * @brief Handles EXTI0 and EXTI1 interrupts.
 ******************************************************************************/
void EXTI0_1_IRQHandler(void);


/******************************************************************************
 * @brief Handles EXTI6 and EXTI7 interrupts.
 ******************************************************************************/
void EXTI4_15_IRQHandler(void);

#endif /* EXTI_H */
